services:
  fastapi:
    container_name: FastAPI
    build: ./fastapi
    command: fastapi dev main.py
    ports:
      - 8000:8000
    depends_on:
      - fastapi-db
  flask:
    container_name: Flask
    build: ./flask
    command: gunicorn -b :5000 --access-logfile - --error-logfile - flask_app:app
    ports:
      - 5000:5000
    depends_on:
      - flask-db
    environment:
      - DATABASE_URL=postgresql://flask_db_user:flask_db_password@db:5432/flask_db
  fastapi-db:
    container_name: FastAPI-Database
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: fastapi_db_user
      POSTGRES_PASSWORD: fastapi_db_password
      POSTGRES_DB: fastapi_db
  flask-db:
    container_name: Flask-Database
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: flask_db_user
      POSTGRES_PASSWORD: flask_db_password
      POSTGRES_DB: flask_db