services:
  fastapi:
    container_name: FastAPI
    build: ./fastapi
    command: fastapi dev main.py
    ports:
      - 8000:8000
  flask:
    container_name: Flask
    build: ./flask
    command: gunicorn -b :5001 --access-logfile - --error-logfile - flask_app:app
    ports:
      - 5001:5001
