# Create a thing
POST http://localhost:5000/v1/things
content-type: application/json

{
  "name": "Apple",
  "colour": "red",
  "quantity": 6
}

###

# List things
GET http://localhost:5000/v1/things

###

# Get a thing
GET http://localhost:5000/v1/things/1

###

# Update a thing
PUT http://localhost:5000/v1/things/1
content-type: application/json

{
  "name": "Apple",
  "colour": "green",
  "quantity": 4
}

###

# Delete a thing
DELETE http://localhost:5000/v1/things/2