# Create a thing
POST http://localhost:6000/v1/things
content-type: application/json

{
  "name": "{{$guid}}",
  "colour": "red",
  "quantity": {{$randomInt 0 100}}
}

###

# List things
GET http://localhost:6000/v1/things

###

# Get a thing
GET http://localhost:6000/v1/things/1

###

# Update a thing
PUT http://localhost:6000/v1/things/1
content-type: application/json

{
  "name": "{{$guid}}",
  "colour": "green",
  "quantity": {{$randomInt 0 100}}
}

###

# Delete a thing
DELETE http://localhost:6000/v1/things/2